## Preprocessing

In [2]:
# Removing just "ORGANIZATION" column
# Original cutoffs
# Adding a 3rd hidden layer of 10 neurons

# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.

application_df.drop(columns=['EIN', 'NAME', 'ORGANIZATION'], inplace=True)

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
AT_counts = application_df['APPLICATION_TYPE'].value_counts()
AT_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff = 100
# List comp. of values under cutoff
application_types_to_replace = [AT for AT, count in AT_counts.items() if count < cutoff]

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
CLASS_counts = application_df['CLASSIFICATION'].value_counts()
CLASS_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
CLASS_over_1 = CLASS_counts[CLASS_counts > 1]
CLASS_over_1

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
CLASS_cutoff = 1000

# List comp. of values under cutoff
classifications_to_replace = [C for C, count in CLASS_counts.items() if count < CLASS_cutoff]


# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [11]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop(columns=['IS_SUCCESSFUL'])
y = application_df['IS_SUCCESSFUL']


# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=17)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
input_feat = X_train_scaled.shape[1]

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=input_feat))


# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Third hidden layer (NEW)
nn.add(tf.keras.layers.Dense(units=10, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3280

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 10)                310

 dense_3 (Dense)             (None, 1)                 11

=================================================================
Total params: 6031 (23.56 KB)
Trainable params: 6031 (23.56 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [15]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5778 - accuracy: 0.7186
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5627 - accuracy: 0.7254
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5605 - accuracy: 0.7264
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5593 - accuracy: 0.7259
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5586 - accuracy: 0.7277
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5583 - accuracy: 0.7273
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5583 - accuracy: 0.7274
Epoch 8/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5574 - accuracy: 0.7283
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5570 - accuracy: 0.7284
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5566 - accuracy: 0.7283
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5564 - accuracy: 0.7280
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5561 - accuracy: 0.7278
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5560 - accuracy: 0.7282
Epoch 14/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5555 - accuracy: 0.7289
Epoch 15/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5551 - accuracy: 0.7285
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5556 - accuracy: 0.7284
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5553 - accuracy: 0.7295
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5551 - accuracy: 0.7276
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5548 - accuracy: 0.7292
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5549 - accuracy: 0.7288
Epoch 21/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5547 - accuracy: 0.7294
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5545 - accuracy: 0.7292
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5544 - accuracy: 0.7292
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5543 - accuracy: 0.7292
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5543 - accuracy: 0.7293
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5539 - accuracy: 0.7293
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5538 - accuracy: 0.7299
Epoch 28/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5539 - accuracy: 0.7296
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5538 - accuracy: 0.7305
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5536 - accuracy: 0.7301
Epoch 31/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5535 - accuracy: 0.7307
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5532 - accuracy: 0.7301
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5532 - accuracy: 0.7299
Epoch 34/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5528 - accuracy: 0.7299
Epoch 35/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5529 - accuracy: 0.7301
Epoch 36/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5529 - accuracy: 0.7300
Epoch 37/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5527 - accuracy: 0.7308
Epoch 38/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5528 - accuracy: 0.7308
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5524 - accuracy: 0.7301
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5522 - accuracy: 0.7307
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5525 - accuracy: 0.7306
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5523 - accuracy: 0.7310
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5521 - accuracy: 0.7306
Epoch 44/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5520 - accuracy: 0.7303
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5519 - accuracy: 0.7304
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5514 - accuracy: 0.7312
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5517 - accuracy: 0.7311
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5514 - accuracy: 0.7322
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5513 - accuracy: 0.7310
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5517 - accuracy: 0.7312
Epoch 51/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5517 - accuracy: 0.7310
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5514 - accuracy: 0.7316
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5513 - accuracy: 0.7313
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5513 - accuracy: 0.7316
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7315
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5514 - accuracy: 0.7301
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5510 - accuracy: 0.7310
Epoch 58/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5510 - accuracy: 0.7308
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5511 - accuracy: 0.7313
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5509 - accuracy: 0.7318
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5505 - accuracy: 0.7317
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5505 - accuracy: 0.7317
Epoch 63/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5506 - accuracy: 0.7315
Epoch 64/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5505 - accuracy: 0.7310
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7319
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5506 - accuracy: 0.7324
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7318
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5501 - accuracy: 0.7318
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7317
Epoch 70/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5502 - accuracy: 0.7317
Epoch 71/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5501 - accuracy: 0.7317
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7322
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5502 - accuracy: 0.7317
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5502 - accuracy: 0.7311
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7316
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7319
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5499 - accuracy: 0.7317
Epoch 78/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5498 - accuracy: 0.7319
Epoch 79/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5498 - accuracy: 0.7327
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5500 - accuracy: 0.7311
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7319
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7327
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7316
Epoch 84/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5500 - accuracy: 0.7322
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5495 - accuracy: 0.7310
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7317
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7324
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7331
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7324
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7320
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5494 - accuracy: 0.7321
Epoch 92/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5494 - accuracy: 0.7321
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5492 - accuracy: 0.7324
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7326
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7320
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7324
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7324
Epoch 98/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5492 - accuracy: 0.7326
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7321
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7324

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5691 - accuracy: 0.7245 - 490ms/epoch - 2ms/step
Loss: 0.5690689086914062, Accuracy: 0.7245481014251709

In [ ]:
# Export our model to HDF5 file
nn.save("model_04.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(